### ISSUE TITLE
"import pyppeteer2" is error! 

### ISSUE THREAD

**Issue by Gamecrazy** [pyppeteer/pyppeteer#102]

**Comment by gyermolenko** [comment]
1. `import pyppeteer`
2. In general it is better to paste error message to receive feedback

**Comment by Gamecrazy** [comment]
thx，Should I install both pyppeter and pyppeter2，then use "import pyppeteer"?

**Comment by gyermolenko** [comment]
> thx，Should I install both pyppeter and pyppeter2，then use "import pyppeteer"?

No. just that
https://github.com/pyppeteer/pyppeteer2#installation
`pip install pyppeteer2`

**Comment by Mattwmaster58** [comment]
See also the usage section. This is pretty clearly documented.
