### ISSUE TITLE
Pyppeteer Browser closed unexpectedly in heroku

### ISSUE THREAD

**Issue by alenpaulvarghese** [pyppeteer/pyppeteer#111]
I recently deployed an app in heroku . It uses python pyppeteer package. I didnt had any issues while testing on repl.it. But unfortunately in heroku the browser keeps crashing.

I used requirement.txt for installing pyppeteer package. I also tried using apt heroku buildpack for installing the requirements needed for pupeteer to work as per [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)

My program :

```
async def mainer(link, path, is_image):
    browser = await launch(args=['--no-sandbox'])
    page = await browser.newPage()
    await page.goto(link)
    if is_image:
        await page.screenshot({'path': f'{path}', 'fullPage': True, 'type': 'png'})
    else:
        await page.pdf({'path': f'{path}'})
    await browser.close()
```

here is the full traceback error from heroku :

```
2020-05-14T19:39:50.115643+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2020-05-14T19:39:50.115644+00:00 app[worker.1]:   File "/app/plugins/downloader.py", line 61, in cb_
2020-05-14T19:39:50.115645+00:00 app[worker.1]:     await mainer(url,file,mode)
2020-05-14T19:39:50.115645+00:00 app[worker.1]:   File "/app/plugins/downloader.py", line 13, in mainer
2020-05-14T19:39:50.115646+00:00 app[worker.1]:     browser = await launch(args=['--no-sandbox'])
2020-05-14T19:39:50.115646+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
2020-05-14T19:39:50.115647+00:00 app[worker.1]:     return await Launcher(options, **kwargs).launch()
2020-05-14T19:39:50.115648+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
2020-05-14T19:39:50.115648+00:00 app[worker.1]:     self.browserWSEndpoint = get_ws_endpoint(self.url)
2020-05-14T19:39:50.115648+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
2020-05-14T19:39:50.115649+00:00 app[worker.1]:     raise BrowserError('Browser closed unexpectedly:\n')
2020-05-14T19:39:50.115649+00:00 app[worker.1]: pyppeteer.errors.BrowserError: Browser closed unexpectedly:
2020-05-14T19:39:50.115650+00:00 app[worker.1]: 
```

**Comment by tburnett** [comment]
I get the same error, both with 0.2.2, and the "latest" 0.0.25 from the repository.
This is with two different Linux systems: Ubuntu and centos 7.

**Comment by tburnett** [comment]
Since it fails in chromium, I tried a different version: 737027 instead of 588429, as specified in __init__.py. Same result.

**Comment by kursataktas** [comment]
I faced the same issue for Ubuntu 18.04 in GCP compute engine, here is my solution;

1- Find the downloaded chrome (`chromiumExecutable `constant variable  in `chromium_downloader.py` shows the path)

2- Run it in bash (`$ /path/to/chrome`)

3- If the result is like this;
   

> error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

4- Run;
`sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
`

I've no idea about step 4, it just worked 🙉

**Comment by Mattwmaster58** [comment]
@kursataktas WRT step 4, those are a bunch of libs chrome depends on to run headlessly. So it's very possible that this is the issue here. See also: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

@alenpaul2001, @tburnett Could you let me know if that works?

**Comment by kursataktas** [comment]
@Mattwmaster58  makes sense, thank you for clarification.

**Comment by alenpaulvarghese** [comment]
> @kursataktas WRT step 4, those are a bunch of libs chrome depends on to run headlessly. So it's very possible that this is the issue here. See also: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
> 
> @alenpaul2001, @tburnett Could you let me know if that works?

i tried installing the dependencies for debian based system , still the browser crash

**Comment by tburnett** [comment]
On my ubuntu system I get
`./chrome: error while loading shared libraries: libxcb-dri3.so.0: cannot open shared object file: No such file or directory`
However, sudo apt-get fails to find that. And this cannot be a solution on the CENTOS system where don't have root privileges.

**Comment by Mattwmaster58** [comment]
@tburnett In your case this isn't a pyppeteer issue per se. Those libs are required by Chrome and their nothing we can do on our end to work around that. You may have some luck putting the libs somewhere and updating your PATH variable to include them. But I'm not experienced in that. Another thing you could try is just googleing around with that error. Here's some (hopefully) related items: 
- https://github.com/heroku/heroku-buildpack-google-chrome/issues/39
- https://github.com/alixaxel/chrome-aws-lambda/issues/93

WRT `apt-get` not finding 'that', instead of trying to install packages based off the library name, I'd recommend following puppeteer's guide to getting Chrome running which can be found [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)

**Comment by tburnett** [comment]
Ok, that link was what I needed, thanks. The list gave the appropriate names to use in apt-get install.
I needed, I think this was all: libgtk-3-0, libxss1, libnss3, libasound2, libgm1, libx1-xcb1.
I needed to translate the launch call to specify --no--sandbox:

`broswer = await launch(args=['--no-sandbox'])`

I tested this on my Ubuntu system. Very unlikely that I would be able to persuade the administrators of the centos systems where I want to use this, and make it available to collaborators, though. I see that apt-get has a local option, looks complicated--maybe a linux expert could weigh it. After all, this headless chrome is local.

The symptom of this issue is that launch call hanging. I wonder if there is a way for you to detect that and provide some useful help?

**Comment by Mattwmaster58** [comment]
In future versions (eg pup2.1.1 branch ATM), the launch call should timeout, and when it does (IIRC) it'll include the Stdout of the process to that point.

**Comment by alenpaulvarghese** [comment]
I found a fix for this issue in heroku. I used this [buildpack](https://github.com/heroku/heroku-buildpack-google-chrome) and added this binary to Executablepath and removed the args from launch

**Comment by firozzer** [comment]
Hi, could you please elaborate on "added this binary to Excecutablepath" bit? This is my code, but it still gives me the browser closed unexepctedly error:

import asyncio
import time
from pyppeteer import launch

async def main():
    browser = await launch({'headless': False, 'userDataDir': "./User_Data"})
    page = await browser.newPage()
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 OPR/68.0.3618.125');
    await page.goto('https://web.whatsapp.com/')
    time.sleep(99)
    # await browser.close()

asyncio.get_event_loop().run_until_complete(main())

**Comment by alenpaulvarghese** [comment]
@XtremePwnership  https://github.com/alenpaul2001/Web-Screenshot-Bot/blob/e031e1b7dbcfce22c29b0886d95cd88fc68fbeb1/plugins/downloader.py#L91 

if u like to know more find me in TG >> [link](https://t.me/StarkTM1) :)

**Comment by rehmatworks** [comment]
> I faced the same issue for Ubuntu 18.04 in GCP compute engine, here is my solution;
> 
> 1- Find the downloaded chrome (`chromiumExecutable `constant variable in `chromium_downloader.py` shows the path)
> 
> 2- Run it in bash (`$ /path/to/chrome`)
> 
> 3- If the result is like this;
> 
> > error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
> 
> 4- Run;
> `sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget `
> 
> I've no idea about step 4, it just worked 🙉

This worked on my Ubuntu server. I am not sure what was the actual solution, but one of the packages that I installed in step 4 did the trick.

**Comment by shyandsy** [comment]
how to fix it on centos 7.5? anyone shows the yum install list?

**Comment by obsd** [comment]
```yum install libXScrnSaver``` fixed that for me on Centos 7 @shyandsy

**Comment by FranckyTang** [comment]
I get the same error，and I find that it is timeout for waiting ws start.
so,I change timeout value bigger
now it worked
```
def get_ws_endpoint(url) -> str:
    url = url + '/json/version'
    
    timeout = time.time() + 300     
    while (True):
        if time.time() > timeout:
            raise BrowserError('Browser closed unexpectedly:\n')
        try:
            
            with urlopen(url) as f:
                data = json.loads(f.read().decode())
            break
        except URLError:
            continue
        time.sleep(0.1)

    return data['webSocketDebuggerUrl']
```

**timeout = time.time() + 300**

**Comment by FranckyTang** [comment]
I found the real reason
My running environment is WSL2 ,it have no UI

```
async def launch(self) -> Browser:  # noqa: C901
        """Start chrome process and return `Browser` object."""
        self.chromeClosed = False
        self.connection: Optional[Connection] = None

        options = dict()
        options['env'] = self.env
        if not self.dumpio:
            # discard stdout, it's never read in any case.
            options['stdout'] = subprocess.DEVNULL
            options['stderr'] = subprocess.STDOUT

        self.proc = subprocess.Popen(  # type: ignore
            self.cmd, **options, )
       .............
```
_self.proc = subprocess.Popen(  # type: ignore  self.cmd, **options, )_

it exec command and will take a long time 

`/home/_username_/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --remote-debugging-port=45641 --user-data-dir=/home/_username_/.local/share/pyppeteer/.dev_profile/tmp5nkxen21`

and throw exception
```
[0114/180018.951343:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.
xcb_connection_has_error() returned true
```
After set DISPLAY environment variable ,it runs very fast
`export DISPLAY=yourXServerIP:0`

it will still throw exception
`[0114/184015.839636:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.`
but there is no **xcb_connection_has_error()** any more

**Comment by vealjoshua** [comment]
> I faced the same issue for Ubuntu 18.04 in GCP compute engine, here is my solution;
> 
> 1- Find the downloaded chrome (`chromiumExecutable `constant variable in `chromium_downloader.py` shows the path)
> 
> 2- Run it in bash (`$ /path/to/chrome`)
> 
> 3- If the result is like this;
> 
> > error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
> 
> 4- Run;
> `sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget `
> 
> I've no idea about step 4, it just worked 🙉

Do I add this to my Procfile? I'm still getting the "Browser closed unexpectedly" error :(

**Comment by artwl** [comment]
> > I faced the same issue for Ubuntu 18.04 in GCP compute engine, here is my solution;
> > 1- Find the downloaded chrome (`chromiumExecutable `constant variable in `chromium_downloader.py` shows the path)
> > 2- Run it in bash (`$ /path/to/chrome`)
> > 3- If the result is like this;
> > > error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
> > 
> > 
> > 4- Run;
> > `sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget `
> > I've no idea about step 4, it just worked 🙉
> 
> Do I add this to my Procfile? I'm still getting the "Browser closed unexpectedly" error :(

add `args=['--no-sandbox']` in launch:

`browser = await launch(args=['--no-sandbox'])`

**Comment by larytet** [comment]
In case anyone needs a Dockerfile for Ubuntu 20.04 https://github.com/larytet-py/headless-chrome

**Comment by alimehran200** [comment]
perfect solution https://blog.csdn.net/wgPython/article/details/102519342

**Comment by glira** [comment]
I solve this error with chmod +x * in chrome directory.
