### ISSUE TITLE
Any way to save/load cache?

### ISSUE THREAD

**Issue by gusgordon** [pyppeteer/pyppeteer#114]
I run pyppeteer on AWS Lambda. One of the problems with running on Lambda is that the functions are short-lived, and whenever the function restarts, the cache (and cookies) start clean.

It would be nice if I could save the cache to S3, then reload the cache the next time the browser launches from a new Lambda function. Is it possible to save and load the cache? Thanks!

**Comment by Mattwmaster58** [comment]
I know the neither pyppeteer nor puppeteer nor playwright have this feature, and glancing at the CDP spec, it's not present, so I can say with confidence that this won't be on the projects radar for _at least_ another year or so. 

I have to admit I'm not well versed in AWS products in general, so I could be wrong on this, but you may be able to store the the cache folder for Chrome in something like S3 (network egress costs might be an issue?) and restore it on lambda startup? Chrome's page cache might not necessarily even be stored on the disk. Maybe consider keeping your Chrome instance running continually 😉 ?
