### ISSUE TITLE
Navigation Timeout Exceeded after clicking logon button.

### ISSUE THREAD

**Issue by fspider** [pyppeteer/pyppeteer#118]
I am going to log in E*trade website.

    await asyncio.gather(*[
        page.evaluate('(element) => element.click()', element),
        page.waitForNavigation(),
    ])

    await asyncio.gather(*[
        page.click("#logon_button"),
        page.waitForNavigation(),
    ])

Both of them, give me Navigation timeout error!

pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 60000 ms exceeded

**Comment by Mattwmaster58** [comment]
Does the login happen successfully when you observe it in a non-headless browser instance? That's usually a very good first step to debug something. It's also possible that it's a bug in pyppeteer waiting for a navigation to happen. Or your credentials are wrong, or you're not putting entering in any credentials. In almost any case, running in non-headless mode will give you actionable information about your problem.

**Comment by fspider** [comment]
Thanks for your fast help.
I solved this problem. This is the solution that I have done for this bug.

            browser = await pyppeteer.launch( headless=False, ignoreHTTPSErrors = True , args = ['--disable-gpu', '--no-sandbox', '--lang=en-US', '--disable-setuid-sandbox', '--disable-dev-shm-usage'] )
 

But I am getting another error. 

    oauth = OAuth1Session(CONSUMER_KEY, client_secret=CONSUMER_SECRET, callback_uri='oob')
    fetch_response = oauth.fetch_request_token(REQUEST_TOKEN_URL) // Problem is here

Here, get timeout error.
![Screen Shot 2020-05-25 at 9 56 05 AM](https://user-images.githubusercontent.com/53686427/82831789-a9046f80-9eb9-11ea-9e8d-62e97a8f2dc9.png)

Why I am getting timeout error here?
It sometimes works and not works

**Comment by Mattwmaster58** [comment]
This isn't even an issue with pyppeteer
