### ISSUE TITLE
--enable-automation

### ISSUE THREAD

**Issue by yuanwenxu** [pyppeteer/pyppeteer#12]
After annotation -- enable automation, the browser can't detect the principle of automation tool

**Comment by Granitosaurus** [comment]
Could you elaborte on this more?

**Comment by yuanwenxu** [comment]
> 您能再详细点吗？
When I use pyppeter to open the browser, I annotate the -- enable automation parameter in the source launch.py file, and the website can't recognize that I'm using the automation tool to access it. I want to know the principle of this? Even after I annotated -- enable automation, can the browser recognize that the automation tool I used to access it?

**Comment by Granitosaurus** [comment]
@yuanwenxu 
I'm not sure I understand you there but the `--enable-automation` chrome/ium parameter is there to so pyppeteer could control chrome. The website you are visiting has no way of know that however so it's unlikely `--enable-automation` is causing any issues for you.

There are numerous ways to detect a headless browser though, for that please refer to https://github.com/MeiK2333/pyppeteer_stealth which patches some pyppeteer browser with stealth strategies so websites couldn't detect that a headless browser is being used.
