### ISSUE TITLE
Coroutine page.pdf is not rendering properly

### ISSUE THREAD

**Issue by alenpaulvarghese** [pyppeteer/pyppeteer#122]
[HowtoMoveth-webshotbot (2).pdf](https://github.com/pyppeteer/pyppeteer/files/4707549/HowtoMoveth-webshotbot.2.pdf)
Perhaps it maybe an issue with youtube, cause the header is sticky anyway to avoid this.
Also some thumbnails of the videos are missing, I already set the wait untill argument but sometimes while loading heavy sites some images wont get loaded. The issue is with pdf only apparently.

code I used to generate PDF:
```
browser = await launch(
                headless=True,
                executablePath=EXEC_PATH
                )
            page = await browser.newPage()
            await page.goto(link, {"waitUtil": 'networkidle0'})
await page.emulateMedia('screen')
await page.pdf{'width': 1280, 'height': 720, 'path': './FILES/584512526/4605/HowtoMoveth-webshotbot.pdf', 'printBackground': True}
```

**Comment by Mattwmaster58** [comment]
What happens when you set your window to the same size and print it
manually? I'm guessing it will look the same. Sites can specify a style
used for printing, but I doubt YouTube has put much effort into having
their page look good when printed.

**Comment by alenpaulvarghese** [comment]
@Mattwmaster58 yeah my bad i am closing it
