### ISSUE TITLE
State of release 0.2.2

### ISSUE THREAD

**Issue by jessrosenfield** [pyppeteer/pyppeteer#133]
Under [PyPi](https://pypi.org/project/pyppeteer/) the latest release is 0.2.2 but the latest release on [this repo](https://github.com/pyppeteer/pyppeteer/releases) seems to be 0.0.25 from almost two years ago. Is 0.2.2 from this repo and will it be reflected in [CHANGES.md](https://github.com/pyppeteer/pyppeteer/blob/dev/CHANGES.md)?

**Comment by Mattwmaster58** [comment]
Sorry for the confusion. The PyPi release of 0.2.2 was to address some critical flaws in pyppeteer and was a bit rushed, hence the missing entry in CHANGES.md. I'd have to check with others, but I'm guessing GitHub releases will not be used going forward because (AFAIK) they provide almost 0 benefit and just become another thing to maintain.

**Comment by jessrosenfield** [comment]
@Mattwmaster58  github releases are very useful for tying a release to the source's version history, which is important for debugging issues. This seems like more than just a documentation issue because the `__init__.py` also has outdated release information.

**Comment by Mattwmaster58** [comment]
@jessrosenfield I think you meant me 😉 ? Anyways, I can see that point, but does it accomplish anything that having the releases on PyPi doesn't?

**Comment by jessrosenfield** [comment]
Actually not a big problem because I can inspect the source in site-packages, but still an inconvenience.

**Comment by jessrosenfield** [comment]
Oops sorry! Fixed the tag

**Comment by polyzen** [comment]
Please tag releases. Trying to figure out which commit is tied to a release is difficult without them, and creates more work when trying to compare releases. This would also make it so people can keep track of tags/releases with a feed reader and/or by following the repo.

**Comment by Mattwmaster58** [comment]
@polyzen that's singing that will absolutely be done in future releases

**Comment by SylvainCorlay** [comment]
It would be fantastic if there was a tag pointing at the commit of the 0.2.2 release. This is really useful to know which commit corresponds to which release!

**Comment by Mattwmaster58** [comment]
@SylvainCorlay @polyzen I've just released an RC, 0.2.3.rc1 which is properly tagged.
