### ISSUE TITLE
RuntimeError('Event loop is closed'),sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited

### ISSUE THREAD

**Issue by LeoonZHANG** [pyppeteer/pyppeteer#143]
here is my code:
async def fuzz_payload(browser, url, method, data, headers, celery_task_id, payload):
    try:
        page = await browser.newPage()
        await page.setRequestInterception(True)
        page.on(
            'dialog',
            lambda dialog: asyncio.ensure_future(
                hook_dialog(dialog, url, method, data, headers, celery_task_id, payload))
        )
        page.on('request', lambda req: hook_request(req, url, method, data, headers, payload))
        await page.goto(url)
        # await asyncio.wait([page.waitForNavigation(),])
        await page.evaluate('() => {var len=document.getElementsByTagName("xss").length;if (len > 0){alert("65534")}}')
        # await asyncio.wait([page.waitForNavigation(), ])
        # await page.close()
    except Exception as e:
        pass
        # if not isinstance(e, NetworkError, ):
        #    logger.exception("fuzz_payload error")

async def fuzz_payloads(payloads):
    try:
        browser = await open_browser()
        if isinstance(payloads, str):
            payloads = [payloads]
        tasks = [
            fuzz_payload(browser, Request.url, Request.method, Request.data, Request.headers, Request.celery_task_id,
                         payload) for payload in payloads]
        await asyncio.wait(tasks)
        await asyncio.sleep(BROWSER_DEAD_TIME)
        await browser.close()
    except Exception:
        pass

def handle_single_process(payloads):
    """
    :param websites: 
    :return: 
    """
    event_loop = asyncio.get_event_loop()
    try:
        event_loop.run_until_complete(fuzz_payloads(payloads))
    finally:
        event_loop.close()

when i run this py, got this erro:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/pyppeteer/launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/local/python3/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self._check_closed()
  File "/usr/local/python3/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/pyppeteer/launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/local/python3/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self._check_closed()
  File "/usr/local/python3/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited

#################
also i use pip install -U git+https://github.com/pyppeteer/pyppeteer@dev
os: centos7.4
python3.6.8

**Comment by elblogbruno** [comment]
I do have the same issue did you fix it?

**Comment by ernests** [comment]
First of all, you should format the comment so your code is actually readable ;)

By looking at the code, I see that you launch browser with

`browser = await open_browser()`

but there cannot be seen parameters for `launch()` in that `open_browser()` function. I encountered the same problem when I had `autoClose: True`. As I understand, it closes Chrome and then you invoke `await browser.close()` but there is nothing to close and you get an error. I fixed this with `autoClose: False`

**Comment by LeoonZHANG** [comment]
> First of all, you should format the comment so your code is actually readable ;)
> 
> By looking at the code, I see that you launch browser with
> 
> `browser = await open_browser()`
> 
> but there cannot be seen parameters for `launch()` in that `open_browser()` function. I encountered the same problem when I had `autoClose: True`. As I understand, it closes Chrome and then you invoke `await browser.close()` but there is nothing to close and you get an error. I fixed this with `autoClose: False`

Finally I reinstall the google chrome by "yum localinstall chromium-81.0.4044.138-1.el7.x86_64.rpm" ,then the erro has gone

**Comment by LeoonZHANG** [comment]
> I do have the same issue did you fix it?

Finally I reinstall the google chrome by "yum localinstall chromium-81.0.4044.138-1.el7.x86_64.rpm" ,then the erro has gone

**Comment by elblogbruno** [comment]
Yum is from centos if I do have Debian 9 which version should I reinstall?😅

**Comment by LeoonZHANG** [comment]
> Yum is from centos if I do have Debian 9 which version should I reinstall

**Comment by LeoonZHANG** [comment]
> Yum is from centos if I do have Debian 9 which version should I reinstall?😅

"apt-get install chromium" with debian

**Comment by jtara1** [comment]
@ernests solution worked. To make it clear and give an eg:

use this option and value in launching the browser

```
browser = await launch({
	'autoClose': False,
})
```

Part of my implementation:

```
from pyppeteer import launch


class PuppeteerRequester(Requester):
	def __init__(self):
		self.log = get_logger(__file__)

		self.browser = None
		self.page = None

	async def init(self):
		self.browser = await launch({
			'userDataDir': CHROME_USER_DIR,
			'autoClose': False,
		})
		self.page = await self.browser.newPage()

		self.page.on('response', self.response_handler)

	async def deinit(self):
		await self.page.close()
		await self.browser.close()

		self.page = None
		self.browser = None
```

**Comment by lonecrane** [comment]
@ernests Works. Cute! Thanks.

**Comment by Tamupiwa** [comment]
Ran into the same "Event loop is closed" error trying to run pyppeteer on amazon linux container. Tried all the solutions suggested but nothing worked. Through trial and error, it turned out to be an installation issue and the following below ended up working for me 

```
sudo amazon-linux-extras install epel -y
yum install -y chromium
yum install -y xorg-x11-server-Xvfb gtk3-devel libnotify-devel nss libXScrnSaver alsa-lib
```
