### ISSUE TITLE
Is there a way to capture network requests?

### ISSUE THREAD

**Issue by hoangvu12** [pyppeteer/pyppeteer#156]
In puppeteer, there is a way to capture all network requests

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', interceptedRequest => {
    if (interceptedRequest.url().endsWith('.png') || interceptedRequest.url().endsWith('.jpg'))
      interceptedRequest.abort();
    else
      interceptedRequest.continue();
  });
  await page.goto('https://example.com');
  await browser.close();
})();
```

I wonder if I can do the same for pyppeteer. Thank you.

**Comment by hoangvu12** [comment]
nvm I found it ....

**Comment by ghost** [comment]
@hoangvu12 can you post the solution?

**Comment by hoangvu12** [comment]
> @hoangvu12 can you post the solution?

Unfortunately, It seems doesn't works to me. I think you can try waitForResponse (In pyppeteer I think It's waitFor. You will need to give a check on pyppeteer document.)

Sorry for my bad english
