### ISSUE TITLE
--allow-running-insecure-content   This parameter does not work in headless mode

### ISSUE THREAD

**Issue by ppwang06** [pyppeteer/pyppeteer#158]
when headless is `False`, This parameter can get result from http request, When the headless is `True`, it does not work,
I found answers to some questions, but I don’t know how to solve them
[Some chrome flags not working in headless mode](https://github.com/puppeteer/puppeteer/issues/3741)

**Comment by Mattwmaster58** [comment]
Yep, looks like the puppeteer team has run into this issue before us. The issue lies in chromium, not in p[yu]ppeteer. Closing this for now until that referenced issue shows some progress.
