### ISSUE TITLE
Installs a global `tests` package?

### ISSUE THREAD

**Issue by hoylemd** [pyppeteer/pyppeteer#161]
Hey folks,

When I install this with pip 

```sh
pip install pyppetteer
```

A package named `tests` is installed into site-packages.

Unfortunately, this takes precedence over importing from a project module named `tests` (for test helpers etc), so when I try to `from tests.helpers import some_helper`, it throws an import error because it's trying to import from that `tests` package in `site-packages` instead of from my project.

Would it be possible to rename that to something like pyppeteer-tests, or just not install it at all? I can't imagine I'm the only one who's ever run into this, and I don't think I should have to rename my `tests` directory to accommodate tests for a library (which honestly, I will never run).

**Comment by Mattwmaster58** [comment]
Yeah, there's no reason it should be installed in the first place. I'd need to check but I think I've changed that already.

**Comment by hoylemd** [comment]
That's good to hear. Is there a new release coming soon? This is actually an upstream dependency for my project, so I'm hoping my immediate dependency can upgrade to a version that doesn't install `tests` soonish.

**Comment by hoylemd** [comment]
little bump here.

Also, I saw #16. Would it be correct to assume there won't be another release to PYPI until that's finished?

**Comment by Mattwmaster58** [comment]
> Also, I saw #16. Would it be correct to assume there won't be another release to PYPI until that's finished?

No, hotfixes are definitely possible. I've made an RC just now - 0.2.3.rc1 - but unfortunately forgot to remove the tests package thing in it. I'll catch it in the final release.

**Comment by Mattwmaster58** [comment]
RC2 does not have this defect.

**Comment by hoylemd** [comment]
Thanks @Mattwmaster58 !

**Comment by Mattwmaster58** [comment]
Just released 0.2.3
