### ISSUE TITLE
Question: What is the Puppeteer version supported by Pyppeteer@0.0.25?

### ISSUE THREAD

**Issue by csreddy** [pyppeteer/pyppeteer#172]
From [__init__.py](https://github.com/pyppeteer/pyppeteer/blob/dev/pyppeteer/__init__.py#L15) it seems that the supported Puppeteer version is v1.6.0.  

The reason I'm asking is because the downloaded chromium version by Pyppeteer is `71.0.3542.0` which is associated with [Puppeteer v1.8](https://github.com/puppeteer/puppeteer/releases/tag/v1.8.0) but `69.0.x`  is associated with [Puppeteer v1.6](https://github.com/puppeteer/puppeteer/releases/tag/v1.6.0)

It seems code may not be correctly updated and I believe the actual supported version is 1.8.
Can someone please confirm if this is correct?

**Comment by Mattwmaster58** [comment]
Yes, it is based on puppeteer 1.6.0.

**Comment by csreddy** [comment]
Thanks. But why does it download different chromium version than expected?
According to Puppeteer the correct version is 69.x
https://github.com/puppeteer/puppeteer/releases/tag/v1.6.0

**Comment by Mattwmaster58** [comment]
It's closest relative would be 1.6.0, but that doesn't mean there aren't any differences. Ideally yes, the chrome executable downloaded would be the same as the version used in puppeteer.
