### ISSUE TITLE
(Temporarily) redirecting issue creators from pyppeteer to here

### ISSUE THREAD

**Issue by Mattwmaster58** [pyppeteer/pyppeteer#18]
I was wondering if it would be worth the trouble to redirect users posting new issues in pyppeteer to here. This would allow to get the word out, but could add to the issue handling workload — though I'm not quite sure how significantly.

**Comment by Granitosaurus** [comment]
Original pyppeteer is unmaintained and the maintainer has disappeared so no one has the control of original repo. We probably could setup a bot auto reply but I'm not sure how would that gell with Github overlords.

**Comment by Mattwmaster58** [comment]
I can do this manually for now. Once we get some momentum I assume less issues will be filed with the abandoned project. Closing this issue for now.
