### ISSUE TITLE
facebook banned

### ISSUE THREAD

**Issue by septfish** [pyppeteer/pyppeteer#183]
Why the headless login is normal in windows, but the account is blocked by facebook when the headless login is normal in linux? What parameters need to be added? Or caused by the environment
surroundings:
windows: Singapore test over the wall
linux: Hong Kong server
Everything else is the same. Could it be that I have some session files locally but not on the linux server?

**Comment by owiofwm2i** [comment]
i think maybe facebook has some js to detect that ,you should try to find it and hack it

**Comment by Mattwmaster58** [comment]
This is beyond the scope of this project
