### ISSUE TITLE
Chrome auto translate page options?

### ISSUE THREAD

**Issue by rosstex** [pyppeteer/pyppeteer#187]
I have found ways to use Chrome's auto-translate option with Selenium (https://stackoverflow.com/questions/54042910/how-can-i-translate-the-webpage-opened-via-selenium-webdriver-to-english-using-p), but not with puppeteer/pyppeteer. Is this supported?

It may have been requested here: https://github.com/puppeteer/puppeteer/issues/1693

**Comment by Mattwmaster58** [comment]
It looks like the feature was out of scope of puppeteer and was instead implemented in this repo: https://github.com/berstend/puppeteer-extra

As one of the goals of this project is to mimic puppeteer closely, this feature also falls out of scope of this project.
