### ISSUE TITLE
uncontrollable chromium process caused by 'http.client.BadStatusLine: GET /json/version HTTP/1.1' exception

### ISSUE THREAD

**Issue by minofmax** [pyppeteer/pyppeteer#188]
```python
browser = await launch(args)
```
Code above may cause  'http.client.BadStatusLine: GET /json/version HTTP/1.1' exception, this exception raised by urllib.urlopen().
In pyppeteer, urlopen used in `launcher.py`, line 222, code just like this
```python
def get_ws_endpoint(url) -> str:
    url = url + '/json/version'
    timeout = time.time() + 30
    while (True):
        if time.time() > timeout:
            raise BrowserError('Browser closed unexpectedly:\n')
        try:
            with urlopen(url) as f:
                data = json.loads(f.read().decode())
            break
        except URLError as e:
            continue
        time.sleep(0.1)
    return data['webSocketDebuggerUrl']
```
the exception belong to http.client.HTTPException, not URLError. so, the `try ... except` can not catch the exception.
In 'launch' method, browser can not be returned successfully.
```python
connectionDelay = self.slowMo
_self.browserWSEndpoint = get_ws_endpoint(self.url)_   # when this method raise exceptions, the following code is unreachable
logger.info(f'Browser listening on: {self.browserWSEndpoint}')
self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )
browser = await Browser.create(self.connection, [], self.ignoreHTTPSErrors, self.defaultViewport, self.proc,
                                       self.killChrome)
await self.ensureInitialPage(browser)
return browser
```
but, the chromium process is launched before. so, I just can't control this process when 'http.client.BadStatusLine: GET /json/version HTTP/1.1' exception occured.
```python
self.proc = subprocess.Popen(  # type: ignore
            self.cmd, **options, )  # launcher.py line 146
```
In my opinion, the browser process should launch after called `Connection` method，this way obey the 'proximity rule' also.

**Comment by minofmax** [comment]
I solve this problem in this way temporarily.
I add `Launcher` in `__init__.py`, so I can call ```Launcher``` class to initialize browser, and then I can get ```self.proc```. When the exception occured, I just kill this uncontrollable process in my code by ```os.kill``` to make sure there is no zombie process after my code finished.
In `__init__.py`
```python
from pyppeteer.launcher import connect, launch, executablePath, Launcher # add Launcher  # noqa: E402
from pyppeteer.launcher import defaultArgs  # noqa: E402

version = __version__
version_info = tuple(int(i) for i in version.split('.'))

__all__ = [
    'connect',
    'launch',
    'executablePath',
    'defaultArgs',
    'version',
    'version_info',
    'Launcher'  # add Launcher in there
]
```

In code, you can call like this
```python
launcher = Launcher(args_dict)  # args_dict is your options
browser = await launcher.launch()
proc = launcher.proc # then you can get the pid of this process, and you can kill this process by pid
```

**Comment by Mattwmaster58** [comment]
That's a good workaround, maybe we'll look into implementing this. In theory the browser process should mercilessly be killed when this happens, but the implementation of that still needs work, evidently.

**Comment by minofmax** [comment]
> That's a good workaround, maybe we'll look into implementing this. In theory the browser process should mercilessly be killed when this happens, but the implementation of that still needs work, evidently.

In my case, another weird thing happened. When the ```BadStatusLine``` exception occured. I also can not get right ```self.proc```, cos it is ```None```. It's so weird.
```python 
self.proc = subprocess.Popen(self.cmd, **options, ) 
```
The code above will certainly return process, and I can get pid by this process.But, actually I got None instead.
So, the way I solve this issue finally  is to add some other argument in args, just like this:
```python
'args': [
            '--disable-extensions',
            '--disable-bundled-ppapi-flash',
            '--disable-web-security',
            '--disable-gpu',
            '--disable-xss-auditor', 
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--allow-running-insecure-content', 
            '--disable-webgl',
            '--disable-popup-blocking',
            '--' + time_stamp
        ]
```  
I add a timestamp to make sure I can find this process by ```ps -ef``` cmd, so, I can kill this process when the exception occured.
I know the method is not the right way to kill the process, but it works. lol

**Comment by Mattwmaster58** [comment]
> I add a timestamp to make sure I can find this process by ps -ef cmd

I like this idea, should be able to make things work cross-platform with [psutil](https://pypi.org/project/psutil/)

**Comment by minofmax** [comment]
> > I add a timestamp to make sure I can find this process by ps -ef cmd
> 
> I like this idea, should be able to make things work cross-platform with [psutil](https://pypi.org/project/psutil/)

Yes, you are right, I will code like this. I also glad to see official solution about the issue. Thanks for your replying.

**Comment by Sunda001** [comment]
hmm i got the same problems

**Comment by minofmax** [comment]
> hmm i got the same problems
May this method can help you solve the problem temporarily.
[how to find zombie process](https://github.com/pyppeteer/pyppeteer/issues/188#issuecomment-728954773)

**Comment by xuzhengzong** [comment]
same problem.  sys: centos6.5  pyppeteet-dev,  i use the screenshot demo, but it return : Browser closed unexpectedly:

**Comment by xuzhengzong** [comment]
this is my code:
`# -*- coding: utf-8 -*-
import asyncio
from pyppeteer import launch

async def main():
    try:
        browser = await launch()
        page = await browser.newPage()
        await page.goto('https://www.baidu.com')
        await page.screenshot({'path': '/home/wwwroot/default/py/baidu.png'})
        await browser.close()
    except BaseException as e:
        print("except is =", e)

asyncio.get_event_loop().run_until_complete(main())`

**Comment by Sunda001** [comment]
> > hmm i got the same problems
> > May this method can help you solve the problem temporarily.
> > [how to find zombie process](https://github.com/pyppeteer/pyppeteer/issues/188#issuecomment-728954773)

what is the value of time_stamp u added there?

**Comment by minofmax** [comment]
> > > hmm i got the same problems
> > > May this method can help you solve the problem temporarily.
> > > [how to find zombie process](https://github.com/pyppeteer/pyppeteer/issues/188#issuecomment-728954773)
> 
> what is the value of time_stamp u added there?

Ummm, U can find the chromium process by the time_stamp. My issue is when the problem occured, pyppeteer launched a chromium process, but I got ```none``` in returned browser. When I run my code in docker, there will be a lot of processes left in docker. So, I try this way to find the zombie processes and kill them.

**Comment by minofmax** [comment]
> this is my code:
> `# -_- coding: utf-8 -_-
> import asyncio
> from pyppeteer import launch
> 
> async def main():
> try:
> browser = await launch()
> page = await browser.newPage()
> await page.goto('https://www.baidu.com')
> await page.screenshot({'path': '/home/wwwroot/default/py/baidu.png'})
> await browser.close()
> except BaseException as e:
> print("except is =", e)
> 
> asyncio.get_event_loop().run_until_complete(main())`

I run ur code in my pycharm, it works. But my pyppeteer version is 0.2.2.
Maybe u can use loop in this way
```python3
tmp_loop = asyncio.new_event_loop()
asyncio.set_event_loop(tmp_loop)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by Mattwmaster58** [comment]
I'm going to mark this fixed-in-2.1.1, it's got much improved launching error handling (it will actaully tell you what went wrong)

**Comment by minofmax** [comment]
> I'm going to mark this fixed-in-2.1.1, it's got much improved launching error handling (it will actaully tell you what went wrong)

wow，it is really helpful for me, thanks

**Comment by Mattwmaster58** [comment]
@minofmax See related issue #179. I believe this issue is because of an outdated chromiuim version

**Comment by minofmax** [comment]
> @minofmax See related issue #179. I believe this issue is because of an outdated chromiuim version

[179](https://github.com/pyppeteer/pyppeteer/issues/179#issuecomment-757097359)
I saw your answer, I tried to upgrade chromium version before, but failed. I will retry it.

**Comment by minofmax** [comment]
> > @minofmax See related issue #179. I believe this issue is because of an outdated chromiuim version
> 
> [179](https://github.com/pyppeteer/pyppeteer/issues/179#issuecomment-757097359)
> I saw your answer, I tried to upgrade chromium version before, but failed. I will retry it.

ummmm, I try to upgrade chromium version, but there is the same problem. The stack info as follow
```shell
msg:Traceback (most recent call last):
  File "multiprocessing_crawler.py", line 725, in main
    browser, proc = asyncio.get_event_loop().run_until_complete(_start_browser(args_dict))
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "multiprocessing_crawler.py", line 689, in _start_browser
    browser = await launcher.launch()
  File "/usr/local/python3/lib/python3.7/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/python3/lib/python3.7/site-packages/pyppeteer/launcher.py", line 228, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

```

**Comment by Mattwmaster58** [comment]
Are you setting the env variable before running your script? Otherwise it uses the old chrome version

**Comment by minofmax** [comment]
> Are you setting the env variable before running your script? Otherwise it uses the old chrome version

I recheck the chromium version, I upgrade the version to the newest. I guess maybe the ```/root/.local/share/pyppeteer/local-chromium``` exist more than one chromium, and I delete the other low version chromium. Then, it works.

**Comment by minofmax** [comment]
> Are you setting the env variable before running your script? Otherwise it uses the old chrome version

evaluate js may cause process hang. The error is
```python3
Traceback (most recent call last):\n  
File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/execution_context.py\", line 99, in evaluateHandle\n    
_obj = await self._client.send('Runtime.callFunctionOn', 
{\npyppeteer.errors.NetworkError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  
File \"multiprocessing_crawler.py\", line 570, in __crawler\n    await page.evaluate(self.button_js)\n 
 File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/page.py\", line 1184, in evaluate\n    
return await frame.evaluate(pageFunction, *args, force_expr=force_expr)\n  
File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/frame_manager.py\", line 308, in evaluate\n    
return await context.evaluate(\n  File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/execution_context.py\", line 53, in evaluate\n    
handle = await self.evaluateHandle(\n  File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/execution_context.py\", line 108, in evaluateHandle\n    
_rewriteError(e)\n  
File \"/usr/local/python3/lib/python3.8/site-packages/pyppeteer/execution_context.py\", line 237, in _rewriteError\n   
raise type(error)(msg)\npyppeteer.errors.NetworkError: Execution context was destroyed, most likely because of a navigation.\n
```

**Comment by JerryChenn07** [comment]
try run it in --no-sandbox mode

```python
opt = {'args': ['--no-sandbox']}
browser = await launch(opt)
```

**Comment by minofmax** [comment]
> try run it in --no-sandbox mode
> 
> ```python
> opt = {'args': ['--no-sandbox']}
> browser = await launch(opt)
> ```

I use it in --no-sandbox mode, but don't work.
The http error maybe caused by network congestion or something else about bad network environment.

**Comment by lihuaxiaoyang** [comment]
> 
> 
> I solve this problem in this way temporarily.
> I add `Launcher` in `__init__.py`, so I can call `Launcher` class to initialize browser, and then I can get `self.proc`. When the exception occured, I just kill this uncontrollable process in my code by `os.kill` to make sure there is no zombie process after my code finished.
> In `__init__.py`
> 
> ```python
> from pyppeteer.launcher import connect, launch, executablePath, Launcher # add Launcher  # noqa: E402
> from pyppeteer.launcher import defaultArgs  # noqa: E402
> 
> version = __version__
> version_info = tuple(int(i) for i in version.split('.'))
> 
> __all__ = [
>     'connect',
>     'launch',
>     'executablePath',
>     'defaultArgs',
>     'version',
>     'version_info',
>     'Launcher'  # add Launcher in there
> ]
> ```
> 
> In code, you can call like this
> 
> ```python
> launcher = Launcher(args_dict)  # args_dict is your options
> browser = await launcher.launch()
> proc = launcher.proc # then you can get the pid of this process, and you can kill this process by pid
> ```

？？？？？

**Comment by lihuaxiaoyang** [comment]
`shell
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    browser = await launch(headless=True,opetions={'args':['--no-sandbox']})
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 292, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

`

**Comment by lihuaxiaoyang** [comment]
```shell
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    browser = await launch(headless=True,opetions={'args':['--no-sandbox']})
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 292, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

```
