### ISSUE TITLE
How can i get iframe's data?

### ISSUE THREAD

**Issue by allemptysheep** [pyppeteer/pyppeteer#191]
i want to get the data in iframe.
so i use open sources

    # 
    user_data_list = list()
    
    browser = await launch({'headless': False})
    page = await browser.newPage()
    
    #
    await page.setViewport(dict(width=1920, height=1080))

    await page.goto(link)
    
    await page.waitFor(1000)
    
    iframe = await page.xpath('//*[@id="cafe_main"]')
    
    print(iframe)

    frame = await iframe[0].contentFrame()

that iframe and frame return this data

[<pyppeteer.element_handle.ElementHandle object at 0x000001990174A588>]
<pyppeteer.frame_manager.Frame object at 0x0000019901600488>

how can i use this data and how can i get?
and i try to many open source in web but there is not work :(

**Comment by Mattwmaster58** [comment]
This is more of a question for StackOverflow. See: https://pptr.dev/#?product=Puppeteer&version=v3.2.0&show=api-class-elementhandle

**Comment by rchua-at-synagie** [comment]
contentframe is also not working for me... Link in Mattwmaster58 is empty right now.
