### ISSUE TITLE
[ERR_TUNNEL_CONNECTION_FAILED] When trying to use auth proxies with pyppeteer

### ISSUE THREAD

**Issue by thestrawberrygod** [pyppeteer/pyppeteer#192]
Tried to use proxies today with pyppeteer but no mater what i did it dint want to work. Here is my code

```browser = await launch({"headless": False, "args": [f"--proxy-server={proxy_host}:{proxy_port}"]})
    context = await browser.createIncognitoBrowserContext()
    page = await context.newPage()
    await page.authenticate(
        {f"username": "{proxy_user}", "password": "{proxy_pass}"}
    )
```
Im not sure if im doing anything wrong.

**Comment by Mattwmaster58** [comment]
The only argument you're providing to `page.authenticate` evaluates to `{"username": "{proxy_user}", "password": "{proxy_pass}"}` . You probably want `{"username": proxy_user, "password": proxy_pass}`. Feel free to reopen if there's an issue with pyppeteer instead.
