### ISSUE TITLE
How can I send POST requests in a pyppeteer session?

### ISSUE THREAD

**Issue by kikikikikinanana** [pyppeteer/pyppeteer#199]
When I enter the page, and i want to login this site.
Instead of logging in by accessing the login form and entering the ID and password, I want to login by sending a POST requests.
How can I do it?

URL: www.abc.com
request header(abc: testtest)
Data: 
aaa:bbb 
ccc:ddd

**Comment by Mattwmaster58** [comment]
It's out of the scope of project to provide an explicit way to do this. You could execute JS that performs the POST request, though
