### ISSUE TITLE
Missing v0.2.2 tag

### ISSUE THREAD

**Issue by H--o-l** [pyppeteer/pyppeteer#200]
Hey!

Thanks for the hard work on this project, I think my team and I will start using it in production in a few weeks!

For now, we work with the version v0.2.2 from PyPI, seen [here](https://pypi.org/project/pyppeteer/#history)

However, I think the corresponding tag v0.2.2 and release are missing inside the GitHub repository, as seen [here](https://github.com/pyppeteer/pyppeteer/tags)

In order to make debug it easier, could the tag be added? Like that we quickly know with which source we are working.

Have a good day!

**Comment by Mattwmaster58** [comment]
I've just released 0.2.3.rc1 - and it's been properly tagged as well.

**Comment by H--o-l** [comment]
@Mattwmaster58 Thanks for the quick answer!
But are you sure you tagged them properly?
Because I don't see these two tags on the GitHub page https://github.com/pyppeteer/pyppeteer/tags
Maybe you tagged them locally but forget to push them?

**Comment by Mattwmaster58** [comment]
Finding the commit to tag for 0.2.2 is hard to do retroactively, just going forward things will be tagged. Is there any reason you would need 0.2.2? 0.2.3 is a hotfix release that shouldn't be much different.

**Comment by H--o-l** [comment]
Because on npm, there was only 0.2.2 back when I open the issue.
But now there is the 0.2.3, I will use it thanks!

About the tag, I still think it's better to have it in Git history, but no strong opinion now.
If you decide to add the tag, maybe the corresponding commit was this one?
https://github.com/pyppeteer/pyppeteer/commit/812c3b99c8025be23f423ab841564cce5ddaee69

**Comment by Mattwmaster58** [comment]
> Because on npm, there was only 0.2.2 back when I open the issue.

Think you mean `pip` ;)

That commit can't be right cause 0.2.2 actually had an issue where the version was 0.0.25 in the package, the correct commit is burried somewhere and I think a missing tag > incorrect tag

**Comment by H--o-l** [comment]
> Think you mean pip ;)

Yes sorry, of course, I mean, `pip` or pypi.

> That commit can't be right cause 0.2.2 actually had an issue where the version was 0.0.25 in the package, the correct commit is burried somewhere and I think a missing tag > incorrect tag

Crap, ok, understood.
