### ISSUE TITLE
Debugging output using pup2.1.1 branch?

### ISSUE THREAD

**Issue by bland328** [pyppeteer/pyppeteer#204]
Using the `pup2.1.1` branch, I'm connecting to an existing browser using `pyppeteer.launcher('chrome').connect()`.

I'm chasing a problem, and hoping to find a way to maximize debug logging output.

I found [older documentation](https://pyppeteer.github.io/pyppeteer/reference.html#debugging) about setting the `logLevel` option to `logging.DEBUG` for the original `pyppeteer.launcher.launch()` and `pyppeteer.launcher.connect()` functions, but this approach doesn't appear to be applicable to `pup2.1.1`.

Hopefully, something equivalent is still possible--can anyone point me in the right direction?

**Comment by Mattwmaster58** [comment]
The branch using the more standard method of logging of just exposing a certain `'pyppeteer'` logger that you should be able to use like so:
```py
logger = logging.getLogger("pyppeteer")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
```

**Comment by bland328** [comment]
Thank you!
