### ISSUE TITLE
Allow later pyee releases

### ISSUE THREAD

**Issue by fabaff** [pyppeteer/pyppeteer#207]
[`pyee-8.1.0`](https://github.com/jfhbrook/pyee/blob/master/CHANGELOG.rst#20201008-version-810) was released awhile ago. Currently `pyppeteer` limits `pyee` to[ `<8.0.0,>=7.0.1`](https://github.com/pyppeteer/pyppeteer/blob/dev/pyproject.toml#L52).

Any change that there is support coming for later `pyee` releases? Thanks

This is an issue for distribution packages. Fedora and NixOS are already shipping `pyee-8.1.0` and this leads to build failures.

**Comment by Mattwmaster58** [comment]
Done

**Comment by ernests** [comment]
@Mattwmaster58 It seems this move has broken Interception functionality in pyppeteer

https://github.com/pyppeteer/pyppeteer/issues/234
