### ISSUE TITLE
Choose a CI for builds

### ISSUE THREAD

**Issue by Mattwmaster58** [pyppeteer/pyppeteer#21]
It looks like we have both TravisCI and Appveyor both have configs in this project. IMO, there's little benefit to having to CIs, and it just adds bloat and maintenance overhead (feel free to correct me if I'm wrong here).

**Comment by Granitosaurus** [comment]
Yup currently CI and tests taking backseat to catchup with 2.2.1 puppeteer API as the changes makes the current tests somewhat obsolote.   
We could refine it for the time to reduce the noise a bit. There's a bit of work on `poetry` branch regarding this.

**Comment by Mattwmaster58** [comment]
Closed via #13
