### ISSUE TITLE
Chromium/Chrome not Going to Page

### ISSUE THREAD

**Issue by davidb28** [pyppeteer/pyppeteer#214]
Using Python 3.8 and Pyppeteer 0.2.5. When I run my code on Jupyter Chromium opens up, but sits on an "about:blank" page and doesn't go to the link provided. I also tried this with Chrome instead of Chromium and I have the same issue. 

My code is:

```
async def main():
        # launches a chromium browser, can use chrome instead of chromium as well.
        browser = await pyppeteer.launch(headless=False)
        # creates a blank page
        page = await browser.newPage()
        #await page.setDefaultNavigationTimeout(0)
        # follows to the requested page and runs the dynamic code on the site.
        options = {'timeout': 15000}
        await page.goto(round_links[x], options)
        # provides the html content of the page
        cont = await page.content()
        await page.close()
        await browser.close()
        return cont
     

# prints the html code
page=(asyncio.get_event_loop().run_until_complete(main()))
```

Pyppeteer doesn't error out, it just stays saying the code is running, but Chromium is not waiting to load a page.

**Comment by davidb28** [comment]
Solved: nest_asyncio was installed on version 1.4.2, I uninstalled and reinstalled with 1.4.3 and it works fine now.

**Comment by HutAC** [comment]
Can you emit the code that works? Thank you

**Comment by HutAC** [comment]
I've been bothered by this issue for two weeks now.
