### ISSUE TITLE
Heroku error after deploying (No module named '_tkinter')

### ISSUE THREAD

**Issue by nachgarcia90** [pyppeteer/pyppeteer#215]
Hello! I have an web app deployed on heroku (using Python), I am using now Pyppeteer to make some automatic jobs in a web site. After deploying I am getting this issue:

Request Method: | GET
-- | --
https://rompepolizas.herokuapp.com/
3.1.4
ModuleNotFoundError
No module named '_tkinter'
/app/.heroku/python/lib/python3.6/tkinter/__init__.py, line 36, in <module>
/app/.heroku/python/bin/python
3.6.12
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python36.zip',  '/app/.heroku/python/lib/python3.6',  '/app/.heroku/python/lib/python3.6/lib-dynload',  '/app/.heroku/python/lib/python3.6/site-packages']

Anyone faced this issue? I already used the buildpacks for chrome and puppeteer but getting same error.

Thanks!!

**Comment by neisor** [comment]
Hello there, 
This does not seem like this package's specific issue, but rather the Heroku's environment's issue. It seems like your Heroku setup does not support Tkinter (Tk).

This link can potentially lead you to a solution:
https://stackoverflow.com/q/41319082

**Comment by Mattwmaster58** [comment]
I think @neisor is right, your issue is unrelated to this lib

**Comment by khasanovmma** [comment]
where answer? what to do?

**Comment by Gage-Lieble** [comment]
I was struggling with the same problem. Turns out that my Vscode automatically imported Tk at the top of one of my files. The solution maybe to sift through all your python files and manually remove any imports of Tk at the top of the file. Good luck!
