### ISSUE TITLE
probable noob mistake...

### ISSUE THREAD

**Issue by schabertrobbinger** [pyppeteer/pyppeteer#219]
I hesitated before posting here because I'm kind of a noob and your application seems to be for stone-cold experts, but I could not get your most simple sample program to run, which was kind of a bummer:

theboss@enigma:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from pyppeteer import launch
>>> async def main():
...     browser = await launch(args=['--no-sandbox'])
...     page = await browser.newPage()
...     await page.goto('https://www.google.com')
...     await page.screenshot({'/home/theboss/': 'example.png'})
...     await browser.close()
... 
>>> 
KeyboardInterrupt
>>> asyncio.get_event_loop().run_until_complete(main())
>>> quit()

produced...nothing. I think I followed directions, pip install pyppeteer followed by a run of the pyppeteer-install script. Not sure what I'm doing wrong or how to debug, so any advice you can give me would be greatly appreciated.

**Comment by Mattwmaster58** [comment]
It's understandable to be confused here, there's a lot of things that could be happening. I'm guessing one of the parts is waiting for another part. Could you leave it run for at least a minute? That way it will likely produce an error that you can act on.

**Comment by schabertrobbinger** [comment]
Sorry, that post was poorly done, the keyboard interrupt gave the wrong impression. I did let it run and it came back to me after a few seconds:

theboss@enigma:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from pyppeteer import launch
>>> async def main():
...     browser = await launch(args=['--no-sandbox'])
...     page = await browser.newPage()
...     await page.goto('https://www.google.com')
...     await page.screenshot({'/home/theboss/': 'example.png'})
...     await browser.close()
... 
>>> asyncio.get_event_loop().run_until_complete(main())
>>> 

Is there a verbosity flag or something which I could pop in somewhere to get some insight?

**Comment by Mattwmaster58** [comment]
If it's returning to the prompt after a few seconds, chances are it's working :) . I can see that you didn't specify a path, so the image won't be saved to the disk. Perhaps you mean this instead?:
```py
 await page.screenshot(path='/home/theboss/example.png')
 ```
 
PS Python kwargs are preferred to JS kwargs

**Comment by schabertrobbinger** [comment]
Of course, you are right. The problem was that I don't know any JS and thought 'path' was supposed to be the directory in which example.png sits. Thank you for correcting my stoopid mistake. Now to figure out how to get past amazon.com's anti-scraping defenses...
