### ISSUE TITLE
when using page.on handle event  rasie coroutine was never awaited

### ISSUE THREAD

**Issue by qiaochao** [pyppeteer/pyppeteer#220]
#### code:
```
    async def handle(self,resp):
        print('hahaha')

    async def login(self,name,pwd):
        await self.constuct()
        page=await self.browser.newPage()
        await page.goto('https://github.com/',{'timeout':60000})
        page.on('request',self.handle)
```

#### exception:
```
RuntimeWarning: coroutine 'GWHandler.handle' was never awaited
  f(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by pyfection** [comment]
I'm having the exact same issue, were you able to resolve it?

**Comment by minofmax** [comment]
When I upgrade pyppeteer version to 0.2.5, get the same problem, but it works on pyppeteer=0.2.2

**Comment by ernests** [comment]
It is related to [pyee](https://github.com/pyppeteer/pyppeteer/issues/234#issuecomment-825444884) version which comes with 0.2.5.. You can downgrade it with `pip install 'pyee==7.0.4' --force-reinstall` and page.on will work.

**Comment by Mattwmaster58** [comment]
I believe it's silently failing with pyppeteer 0.2.2, and just failing more loudly with 0.2.5. We're not using AsyncIOEventEmitter (yet) so async callback functions aren't possible to use (yet).

**Comment by markfinn** [comment]
Wrapping it with asyncio seems to work fine:

```python
page.on('request', lambda req: asyncio.ensure_future(requesthandler(req)))
```

**Comment by lonecrane** [comment]
> Wrapping it with asyncio seems to work fine:
> 
> ```python
> page.on('request', lambda req: asyncio.ensure_future(requesthandler(req)))
> ```

Works fine. Cute!
