### ISSUE TITLE
3rd party resource and timeouts

### ISSUE THREAD

**Issue by electrofloat** [pyppeteer/pyppeteer#236]
Hi!

Sorry if this has been a known thing or discussed before, just point me to the right direction then and close this issue.

So I monitor a web page which renders content mostly with javascript and no matter how much timeout I give I always have a random diff (diff to the previous render) where I can see that the content which should have been rendered by javascript is not rendered at all. Only the static html is in the output.

I can just only assume that when a 3rd party resource cannot be downloaded (network error/timeout/whatever) it just silently skips it and gives back the static page.

The page without the dynamically rendered content is completely useless to me and just messes up the diff output I have.

Is there a way to tell pyppeteer to either retry downloading the 3rd parties and rerender if it already succeeded to download the 1stparty page within the timeout, or just do not give back anything (handle it as an error/timeout whatever) when it was not able to download/render everything on the page?

Thanks.

**Comment by Mattwmaster58** [comment]
I'd launch the browser in headed mode and see what exactly is failing and what is causing those things to fail. There's no feature of pyppeteer that I'm aware to do exactly what you're trying to do.
