### ISSUE TITLE
Relax importlib-metadata version dependency

### ISSUE THREAD

**Issue by duburcqa** [pyppeteer/pyppeteer#244]
It seems that `importlib-metadata` version was restricted to versions <3.0.0 because of `tox` dependency, itself enforcing such restriction, as mentioned [here](https://github.com/pyppeteer/pyppeteer/blob/f89052763de15c029ab647b150856c3ea80f45dc/pyproject.toml#L50). The required patch of `tox` to support  any version of `importlib-metadata`has been merged on master and is available on `Pypi`. Thus it is now possible to remove this constraint on `pyppeteer`.

**Comment by Mattwmaster58** [comment]
Done, I even had a todo in the code for this moment :)

**Comment by duburcqa** [comment]
Perfect ! Thank you
