### ISSUE TITLE
Crash on running the example screenshot script from the documentation in VSCode Windows 10

### ISSUE THREAD

**Issue by iSaluki** [pyppeteer/pyppeteer#248]
So I installed pyppeteer from Pip, and copied this example script from the docs:

 ```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('http://google.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

However, when I run this code, I get the following errors:

```Traceback (most recent call last):
  File "web.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "web.py", line 5, in main
    browser = await launch()
  File "C:\Users\coinl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyppeteer\launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\coinl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyppeteer\launcher.py", line 147, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
```

On the first run, it did install Chromium and everything, but it still returned this error when it tried to run. Is this a problem with the code, the module, or my setup?

Some helpful details:

-  **Python version:** 3.8.3
-  **Operating System:** Windows 10
- **Pyppeteer Version:** 0.2.5 (Pip)

**Comment by Mattwmaster58** [comment]
Googling that last line of the stack trace may lead to solutions. I believe the download may have been corrupted.

**Comment by iSaluki** [comment]
I have tried a fair number of fixes and spent a few hours on it. In the end I did manage to fix it, but Pyppeteer wasn't loading the page I needed properly, so I'm currently using Puppeteer (which is definitely not ideal, but it does at least work out of the box for me).

A corrupted download could well have been the problem, because completely reinstalling Python (to a later version) and then reinstalling Pyppeteer after changing a few system level settings got it working.

**Comment by tomvik** [comment]
If anyone is having this issue; what fixed it for me was to uninstall the python version downloaded from the windows store and install python directly from their webpage. After doing so, I was able to launch Chromium using Pyppeteer.

**Comment by gieoon** [comment]
> If anyone is having this issue; what fixed it for me was to uninstall the python version downloaded from the windows store and install python directly from their webpage. After doing so, I was able to launch Chromium using Pyppeteer.

This fixed it for me

**Comment by pjgpetecodes** [comment]
> > If anyone is having this issue; what fixed it for me was to uninstall the python version downloaded from the windows store and install python directly from their webpage. After doing so, I was able to launch Chromium using Pyppeteer.
> 
> This fixed it for me

Likewise... This was the fix for me too.
