### ISSUE TITLE
Does not work with latest Chromium

### ISSUE THREAD

**Issue by MatrixRanger98** [pyppeteer/pyppeteer#260]
I manually replaced the old Chromium with the latest one (Version 92.0.4503.0) and it did not work anymore.

It says
```
File "~/anaconda3/lib/python3.8/site-packages/pyppeteer/page.py", line 1444, in pdf
    result = await self._client.send('Page.printToPDF', dict(
pyppeteer.errors.NetworkError: Protocol error (Page.printToPDF): Show invalid printer settings error
```

**Comment by Mattwmaster58** [comment]
Yes, that's why specific chromium builds are pinned to certain versions. Once the codebase is updated, so is the chromium binary accordingly

**Comment by JavaScriptDude** [comment]
FYI - There was a bug in chromium and there has been activity with google on this lately: 
- https://github.com/GoogleChromeLabs/chromium-bidi/issues/518
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=3517
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=4070
