### ISSUE TITLE
Changing pyppeteer's logging configuration

### ISSUE THREAD

**Issue by franz-see** [pyppeteer/pyppeteer#280]
How do I change pyppeteer's logging configuration? 

For example,what if I want to use my custom JsonFormatter so that the logs are structured. 

Thanks

**Comment by Mattwmaster58** [comment]
This isn't really a bug w/ pyppeteer, more a question about how to use the logging module: https://docs.python.org/3/howto/logging-cookbook.html#multiple-handlers-and-formatters

Basically it comes down to, grabbing the logger object with `logging.getLogger("pyppeteer")`, then using formatters and handlers to do what you want with it.
