### ISSUE TITLE
better version of waitUntil: 'networkidle0' or 'networkidle2'

### ISSUE THREAD

**Issue by pradyjswl** [pyppeteer/pyppeteer#282]
I understand that,
networkidle0: when there are no more than 0 network connections for at least 500 ms.
networkidle2: when there are no more than 2 network connections for at least 500 ms.

what if I want to only intercept until there are at least x(say 5) requests in 1 second?

**Comment by Mattwmaster58** [comment]
This is out of scope of the project. You could intercept all requests and update a global counter until a threshold is reached
