### ISSUE TITLE
Relax websockets requirements

### ISSUE THREAD

**Issue by JMante1** [pyppeteer/pyppeteer#285]
pyppeteer 0.2.5 depends on websockets<9.0 and >=8.1 is causing issues because this means pyppeteer can only use websockets8.1 as a release and this has security vulnerabilities.

**Comment by weltonrodrigo** [comment]
There is a CVE of high severity for websocket <9.1 https://github.com/advisories/GHSA-8ch4-58qp-g3mp

**Comment by ajschmidt8** [comment]
For awareness, this issue is similar to https://github.com/pyppeteer/pyppeteer/issues/275

**Comment by Mattwmaster58** [comment]
See specifically: https://github.com/pyppeteer/pyppeteer/issues/275#issuecomment-898995873
