### ISSUE TITLE
Any plan to catchup with latest puppeteer?

### ISSUE THREAD

**Issue by vishalv26** [pyppeteer/pyppeteer#288]
Hi,

Is there a plan to catchup with latest puppeteer development. pyppeteer needs to support latest chromium builds.

Thanks

**Comment by cristianoccazinsp** [comment]
Wondering the same.

**Comment by Mattwmaster58** [comment]
I would say there's a desire by me at least to reach feature parity but at this time I simply don't have the time. Contributions are always welcome, though! If you're planning to try and help pyppeteer reach a version feature parity I'd ask that you communicate on the element server

**Comment by Mattwmaster58** [comment]
This can easily be searched and I think I've answered the question so I'm closing - feel free to reopen if you think otherwise

**Comment by vishalv26** [comment]
Can we get some tutorial about what exactly changes and how to upgrade to latest. Steps or some sort of help

**Comment by Mattwmaster58** [comment]
- checkout the puppeteer repo
 - checkout latest pyppeteer branch (pup2.1.1)
 - makes changes as necessary
 
 This is extremely broad, upgrading will require many hours of work
