### ISSUE TITLE
the default chromium version "588429" is too old, it's better to change a new one.

### ISSUE THREAD

**Issue by heliping** [pyppeteer/pyppeteer#291]
My web site said the chromium can't support, I changed a newer chromium version. need update the __init__py --->  __chromium_revision__ .

**Comment by zak427zak** [comment]
I agree, I faced the same problem

**Comment by Mattwmaster58** [comment]
One can easily change the env variable PYPPETEER_CHROMIUM_REVISION to download whatever revision they please. Until a proper test suite is being used, this can't safely be addressed in my mind, especially with the presence of the aforementioned work-around. A codebase rework and new tests will come around the same time so I'm closing this for now.

https://github.com/pyppeteer/pyppeteer/blob/18bddf4fb28e930f30d80b9806948f499641ebe3/pyppeteer/chromium_downloader.py#L25

**Comment by vee-varun** [comment]
Refer to [this](https://docs.google.com/document/d/1vdGRv35udoKKog0mnVmx5Mh9brRc0qQjvLPZPZyJKOY/edit?usp=sharing) doc to see how to update chromium version in pyppeteer.
