### ISSUE TITLE
PageError: net::ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by python-vlad** [pyppeteer/pyppeteer#296]
Run the code from the example:
```
import asyncio
from pyppeteer import launch


async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://www.tiktok.com/@justinbieber')
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```
I get the error:

>   File "/home/PycharmProjects/First/Start.py", line 8, in main
>     await page.goto('https://www.tiktok.com/@justinbieber')
>   File "/usr/local/lib/python3.8/dist-packages/pyppeteer/page.py", line 879, in goto
>     raise PageError(result)
> pyppeteer.errors.PageError: net::ERR_INVALID_RESPONSE at https://www.tiktok.com/@justinbieber

Opens other links correctly. How do I fix the error?

UPD (12.08.2021):

If you turn off the browser hide mode, then everything works:

`browser = await launch(headless=False)`

**Comment by Mattwmaster58** [comment]
I suspect this has to do with TikTok detecting chromium being controlled by pyppeteer and messing up the response. ERR_INVALID_RESPONSE is a Chrome error, not a pyppeteer error. That's not to say pyppeteer can't cause that error by I think it's unlikely

**Comment by python-vlad** [comment]
> 
> 
> I suspect this has to do with TikTok detecting chromium being controlled by pyppeteer and messing up the response. ERR_INVALID_RESPONSE is a Chrome error, not a pyppeteer error. That's not to say pyppeteer can't cause that error by I think it's unlikely

Yes, I understand. At the same time, if you disable headless mode, then this error does not occur.

Checked on the original puppeteer (JavaScript): it gets this error in headless mode. But if you use the puppeteer-extra-plugin-stealth plugin, then there is no error in headless mode. Maybe you can take something from this plugin to get around this error?

**Comment by Mattwmaster58** [comment]
That's out of the scope of this project unfortunately so I'm closing this for now. I don't think it would be too hard to look into how that stealth plugging add-on does its thing and implement with pyppeteer, maybe you could even make a port while you're at it 😉
