### ISSUE TITLE
Release 0.2.6 missing from PyPi

### ISSUE THREAD

**Issue by mborsetti** [pyppeteer/pyppeteer#298]
I saw that release 0.2.6 was posted at https://github.com/pyppeteer/pyppeteer/releases/tag/0.2.6 (thanks!!), however for some reason [PyPi](https://pypi.org/project/pyppeteer/#history) still only has 0.2.5

**Comment by Mattwmaster58** [comment]
https://github.com/pyppeteer/pyppeteer/issues/275#issuecomment-898995873

😉
