### ISSUE TITLE
launch hangs in Python 3.10

### ISSUE THREAD

**Issue by mborsetti** [pyppeteer/pyppeteer#305]
The following test code works fine in Python 3.9 but **hangs** in Python 3.10, at the line `browser = await launch()`:

```
import asyncio
from pyppeteer import launch
async def pyppeteer_test():
    print('about to launch pyppeteer')
    browser = await launch()
    print('browser launched!')
    await browser.close()
asyncio.run(pyppeteer_test())
```

The above was tested using `pyppeteer` installed using

- `pip install pyppeteer` and 
- `pip install -U git+https://github.com/pyppeteer/pyppeteer@dev`

with `Python 3.10.0rc1 (tags/v3.10.0rc1:cc115e5, Aug  3 2021, 15:22:01) [MSC v.1929 64 bit (AMD64)] on win32`.
 
Both hung _forever_ after printing '`about to launch pyppeteer`'.

**Comment by uraid** [comment]
Same in stable Python 3.10 released 2 days ago.

**Comment by uraid** [comment]
Seems that #321 solves this problem.
Just run:
`pip3 install websockets -U`
To upgrade the websockets package.
Pip will complain pyppeteer requires older websockets but just ignore it.
Tested and working.

**Comment by LeMoussel** [comment]
According to my test With Python 3.7, pyppeteer support websockets up to version 8.1, according to `poetry.lock` file, version 9.0 is supported though (not work in my test).

Same issue I have experienced, it's gone once I downgrade websockets to 8.1 (`pip install websockets==8.1`)

**Comment by SoftCreatR** [comment]
I had the same problem, but upgrading websockets to `10.1` (using Python 3.10.1) worked for me.

**Comment by Mattwmaster58** [comment]
Sorry for the delay, I plan to push a hotfix to update this dep tomorrow

**Comment by Mattwmaster58** [comment]
Just pushed 1.0.0 which fixes this
