### ISSUE TITLE
Release 0.2.6 missing from conda-forge

### ISSUE THREAD

**Issue by mnowacki-b** [pyppeteer/pyppeteer#310]
Looks like version 0.2.6 is only available on [PiPy](https://pypi.org/project/pyppeteer/#history). 
Would it be possible to get it  published to [conda-forge](https://anaconda.org/conda-forge/pyppeteer/files) as well?
Thank you!

**Comment by Mattwmaster58** [comment]
We as maintainers don't control conda-forge packages. I'm not sure who to contact over that, but it isn't us right now.

**Comment by wolfv** [comment]
The right place to ask is probably the conda-forge feedstock :) https://github.com/conda-forge/pyppeteer-feedstock/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
