### ISSUE TITLE
Support type checking with `mypy`

### ISSUE THREAD

**Issue by queensferryme** [pyppeteer/pyppeteer#314]
First of all, thank you for adding such complete type annotations to pyppeteer.

However, users of pyppeteer might not be able to take full advantage of this type-annotated code base with some type-checking tools, such as `mypy`.
```
rsserpent/utils/http.py:5: error: Skipping analyzing "pyppeteer": found module
but no type hints or library stubs  [import]
    from pyppeteer import launch
```

The solution is simple: add an empty file named `py.typed` to the `pyppeteer` directory.

References:
- [PEP 561](https://www.python.org/dev/peps/pep-0561/)
- [Mypy Docs: Using installed packages with mypy (PEP 561)](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages)

**Comment by Mattwmaster58** [comment]
The main issue here is that the type annotations right now for the codebase are incomplete - so I'm not sure if mypy would even be able to benefit or if it would complain about this more.

**Comment by queensferryme** [comment]
Thanks for the clarification - will close for now :)
