### ISSUE TITLE
Q: is it still alpha? What's the criteria for becoming beta?

### ISSUE THREAD

**Issue by d33tah** [pyppeteer/pyppeteer#320]
Hi,

Thanks for developing Pyppeeteer! I've found it very useful on many occasions, where [Selenium just falls short](https://www.selenium.dev/documentation/worst_practices/).

It's tempting to use this in production, but I just noticed that this software is still marked as Alpha:

https://github.com/pyppeteer/pyppeteer/blob/dev/pyproject.toml#L17

Is there a solid reason for this, or is this because this tag wasn't updated for a while? Is there an idea of a point at which it could be called beta?

**Comment by Mattwmaster58** [comment]
Tons of things are still broken, nobody (yet) has been able to put in a consistent effort to maintain it. The code base has tons of failing tests, and poor coverage.
