### ISSUE TITLE
stuck on await browser.newPage()

### ISSUE THREAD

**Issue by odra** [pyppeteer/pyppeteer#330]
Hello,

I am trying to run the basic example from the README.md file but it is getting stuck at `await browser.newPage()`.

Here is my python code:

```
#!/usr/bin/env python
import asyncio
from pyppeteer import launch


async def main():
    print(1)
    browser = await launch(headless=True)
    print(2)
    page = await browser.newPage()
    print(3)
    await page.goto('https://tradingview.com')
    print(3)
    await browser.close()
    print(4)


if __name__ == '__main__':
    asyncio.run(main(), debug=True)
```

The output of my script is (never goes beyond the newPage method):

```
1
Executing <Task pending name='Task-1' coro=<main() running at /home/lrossetti/Work/odra/b3/./tv.py:8> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7febccddcb80>()] created at /usr/lib64/python3.9/asyncio/base_events.py:424> cb=[_run_until_complete_cb() at /usr/lib64/python3.9/asyncio/base_events.py:184] created at /usr/lib64/python3.9/asyncio/base_events.py:621> took 0.212 seconds
2
```

I am using python 3.9 but I got the same error in python 3.10.

Am I missing something?

Thanks!

**Comment by urmzd** [comment]
Experiencing the same thing. Except, mine doesn't even launch, it just hangs :/ Using Python 3.10

**Comment by bravier** [comment]
Hi, if you didn't found the solution already, this might help: https://github.com/pyppeteer/pyppeteer/issues/305#issuecomment-946366914 (you need to update the `websockets` package)

**Comment by odra** [comment]
I gave it a try and it didn't work (using virtualenv).

**Comment by Mattwmaster58** [comment]
1.0.0, which I just pushed should fix this

**Comment by odra** [comment]
Works like a charm, thanks for working on this.
