### ISSUE TITLE
using pyputter on docker giving failure

### ISSUE THREAD

**Issue by yaron-shamul** [pyppeteer/pyppeteer#341]
Hi everyone, I'm running on docker (image is python:3.9) this piece of code belloew:

```
        import pyppdf.patch_pyppeteer
        import requests
        import requests_html

        asession = requests_html.AsyncHTMLSession()`

        playlist_page = await self.fetch_playlist_url(asession)
        if playlist_page.status_code == 200:
            try:
                # execute the java-script
                await playlist_page.html.arender(timeout=DEFAULT_RENDER_TIMEOUT)

            except TimeoutError:
               ...

```

I'm getting this error:

and I've been tried to run the chrome driver itself with the flags as mentioned [https://github.com/pyppeteer/pyppeteer/issues/108#issuecomment-628320088](here) like that:
```
 multi-convertor/local-chromium/588429/chrome-linux/chrome 
--no-sandbox 
--single-process 
--disable-dev-shm-usage 
--disable-gpu 
--no-zygote
```
and got:
`multi-convertor/local-chromium/588429/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

**Comment by ericz15** [comment]
@yaron-shamul maybe this article can help u：https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by yaron-shamul** [comment]
Thank you 🙏
