### ISSUE TITLE
Importing pyppeteer configures logging

### ISSUE THREAD

**Issue by simonpercivall** [pyppeteer/pyppeteer#343]
Regression introduced in 3018414 in `pyppeteer/__init__.py` and published in version 1.0.0.

It seems importing pyppeteer configures logging globally for the Python process, which is something a library should _never_ do. I'd argue that a library shouldn't even configure its _own_ logger, since that will cause applications using the library to start logging stuff they would not want.

Configuring logging should be left to the _application_ using a library, since the application known where and how logs should be displayed.

If this was added to make it easier for less experienced users to see what's going on, I can recommend instead having a documentation section that explains how they can display logs.

(Either way, thanks for developing this library.)

**Comment by Mattwmaster58** [comment]
I agree, sorry I missed this with the last release.

**Comment by Mattwmaster58** [comment]
fixed in 1.0.1
