### ISSUE TITLE
Time delay for dynamic html

### ISSUE THREAD

**Issue by ghost** [pyppeteer/pyppeteer#371]
I want something like
 response.html.render(sleep = 34) 
can anyone help me?

**Comment by brunetton** [comment]
Do **NOT** use issues for questions ! This is NOT an issue; this is a question !

Use google, and find similar questions in Stackoverflow https://stackoverflow.com/questions/46948489/puppeteer-wait-page-load-after-form-submit

So, more than one way to do it. The most simple is to try `await asyncio.sleep(delay=10)` to wait 10 seconds
