### ISSUE TITLE
Make code block full width when building PDF from HTML

### ISSUE THREAD

**Issue by giswqs** [pyppeteer/pyppeteer#372]
Related issue: https://github.com/executablebooks/jupyter-book/issues/1681

### Describe the bug

**context**
I am building a book written in MyST. How can I make the code block full width when building book PDF?

**expectation**
This is what the HTML looks like. The code blocks are in full width. 

![image](https://user-images.githubusercontent.com/5016453/160496684-16effc26-2491-47c5-8560-ce9c3ad6e3c1.png)

**bug**
This is what the PDF looks like when built with `pyppeteer`. The code blocks are in center alignment, not full width 

![image](https://user-images.githubusercontent.com/5016453/160503417-84039cb4-72a4-46a0-90a3-0eaf902697f7.png)

### Reproduce the bug

1. Build book HTML with `jupyter-book build .`
2. `pip install pyppeteer`
3. `jupyter-book build . --builder pdfhtml`

**Comment by Mattwmaster58** [comment]
Is the print style sheet different?

**Comment by giswqs** [comment]
I did not change anything. I just using all the default settings and ran the commands mentioned above. Everything looks fine on the HTML, but not the pdf.

**Comment by Mattwmaster58** [comment]
What happens when you print to a PDF in a regular browser

**Comment by giswqs** [comment]
Interesting to know. Printing the HTML to PDF using Chrome has the same issue. So this could be an issue with the HTML? But the HTML looks fine. The code blocks are in full width. 

![image](https://user-images.githubusercontent.com/5016453/160897216-54eb99b1-f1ee-429e-a6c4-2637c5ae3537.png)

**Comment by giswqs** [comment]
It took me an hour to debug and, finally, I figured it out. The issue is caused by the `{code-cell}` directive in MyST. The code blocks in PDF will render correctly if the  `{code-cell}` directive is not being used. 

![image](https://user-images.githubusercontent.com/5016453/160907177-9f78ccd6-b7a8-4993-8be0-5e960fbbf75e.png)
![image](https://user-images.githubusercontent.com/5016453/160906972-de676c1b-13bb-42ec-b1da-3f752af9600e.png)

![image](https://user-images.githubusercontent.com/5016453/160907395-582f01a5-5a03-49c9-81e3-4b1ac481baf4.png)
![image](https://user-images.githubusercontent.com/5016453/160907450-185c2c36-6bc2-4085-9f22-7f611dbf4566.png)
