### ISSUE TITLE
Intercept Network Requests after user behavior

### ISSUE THREAD

**Issue by tonyrb** [pyppeteer/pyppeteer#393]
Hello,

I am trying to reproduce this behavior:
- User go to a page
- User accept the cookie banner
- User reload the page

at the end of the process I am interested to get all network requests and save them.

So far I am lost, 
I have managed to capture all network request only when the user land on the page the first time but not when the page reload.
When user click on the cookie banner additional network requests appears and here I am stuck with the first arrival without the new one based on his action.

below the code used

```
final_file_list_one_gtm2 = []

for url in cmp_enabled[0:2]:

    request_listing = []
    gtm_ids = []
    onetrust = []

    def logit(event):
        req = event._request

        if 'GTM-' in req.url:
            gtm_ids.append(req.url.split('id=')[1])
            
        elif 'cdn.cookielaw.org' in req.url:
            onetrust.append("true")
            
        else:
            pass
                
                

    async def main():
        browser = await launch({"headless": True})
        page = await browser.newPage()
        
        try:

            urlo = "http://"  + url['url']
            
            await page.goto(urlo, {'waitUntil': 'networkidle0'})
            
            button = await page.querySelector("#onetrust-accept-btn-handler")

            await button.click()
            
            await page.reload()

            page._networkManager.on(NetworkManager.Events.Response, logit)

            print("%s" % url)
            await browser.close()
            
        except (PageError, TimeoutError) as e:
            error_url.append(
                { 'url' : url,
                'reason' : e} )
        
        time.sleep(1)
    asyncio.get_event_loop().run_until_complete(main())
```

Thanks for any help !

**Comment by ernests** [comment]
Here is how I do it and it works.

Define intercept function:

```python
async def intercept_network_response(response):
   print (response.url)
```
Give `page` object command what to do on response

```python
page.on('response', lambda res: asyncio.ensure_future(intercept_network_response(res)))
``` 

Launch your script to do whatever you want and every response will go through intercept function. Works for me. 
Your code is similar but I don't get why you are using `._networkManager`. Couple of other differences. `logit` function is not an async function. I don't know if it should be. Your `page.on` is after `page.goto`. My bet would be that you should move your `page._networkManager` right after you define page object.

**Comment by tonyrb** [comment]
@ernests well you win the bet :). Just had to move my bits right after like proposed and now work like a charm !  thanks !
