### ISSUE TITLE
Error Message: OpenBSD7 not supported (Seriously?)

### ISSUE THREAD

**Issue by anoduck** [pyppeteer/pyppeteer#399]
Pyppeteer is apparently growing in popularity, because I have encountered this issue several times with other packages. It is affecting my ability to develop python programs at this time. I am unsure why OpenBSD is not supported, since chromedriver is supported for OpenBSD, along with selenium.

I am going to fork the project and see if I can get it to successfully build on my system. I do not see a reason, why it should not.

**Comment by Mattwmaster58** [comment]
If you can install chromium yourself you can easily use it. The reason is
because work hasn't been put in to grab bsd binaries.

**Comment by anoduck** [comment]
> 

There in lies the crux of the issue. On my System, Chromium/iridium has stopped functioning completely. Something to do with my video driver.

**Comment by Mattwmaster58** [comment]
You can likely still run headlessly

**Comment by anoduck** [comment]
@Mattwmaster58 Well, eating a nice helping of crow over here... Sometimes, it just takes someone pushing me in the right direction, to finish cognition. I appreciate it.

Broke out the editor and modified "chromium_downloader.py" added three lines of code, and viola pyppeteer is alive at last. I did not know you could ascribe class attributes to a variable, i.e. `chromium_executable = Path(sys.prefix) / 'bin' / 'chrome'`. That is really cool, and will help me in coding.

Furthermore, If chromium_downloader is configured to download the binary from BSD distribution repositories, you could achieve complete compatibility with all three major distributions of BSD.
