### ISSUE TITLE
how to run (chromium, and thus) pyppeteer on ARM64?

### ISSUE THREAD

**Issue by piramiday** [pyppeteer/pyppeteer#404]
hello folks, I was hoping to run `pyppeteer` on a fresh Ubuntu 22.04 ARM64 server, but I get:

```
OSError: [Errno 8] Exec format error: '/home/username/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome'
```

maybe the Chromium executable is x64 only? any suggestions?
if that is the issue, is there a way to manually download -- as opposed to relying on `pyppeteer-install` -- an ARM64-capable build of Chromium?

thanks!

**Comment by Mattwmaster58** [comment]
If you replace the binary found at that location it will be used instead. Matching the revision isn't strictly necessary.

**Comment by piramiday** [comment]
do you know how to install Chromium for ARM64 on Ubuntu, not involving the snap store?

**Comment by piramiday** [comment]
I have installed Chromium through manually satisfying the dependencies of the DEB package obtained here:
https://launchpad.net/ubuntu/bionic/arm64/chromium-browser/104.0.5112.101-0ubuntu0.18.04.1
so as to avoid the transitional package that installs through `snap` in more recent Ubuntu versions.

I do get a seemingly working Chromium:
```
user@host:~$ chromium-browser --version
Chromium 104.0.5112.101 Built on Ubuntu , running on Ubuntu 22.04
```
I then symlinked the `chrome` executable to my new `chromium-browser`:
```
user@host:~$ ln -sfv $(which chromium-browser) ~/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome
'/home/username/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome' -> '/usr/bin/chromium-browser'
```
now, whenever I run my script, the terminal hangs without any output. when I kill it, I get:
```
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
any suggestions?

EDIT: my script works fine in x64 archs, of course.

**Comment by piramiday** [comment]
fixed by adding the `--no-sandbox` launch argument.

any further insight into the problem or better solution is still welcome, but I'm closing the issue for now.
