### ISSUE TITLE
how to send websocket frame

### ISSUE THREAD

**Issue by vinifr** [pyppeteer/pyppeteer#407]
Hello,

How can I send a websocket frame using pyppeteer?  I found this but in javascript:

```
const prototype       = await page.evaluateHandle("WebSocket.prototype");
  const socketInstances = await page.queryObjects(prototype);
  await page.evaluate((instances) => {
    let instance = instances[0];
    instance.send('Hello');
  }, socketInstances);
```

**Comment by Ochmar** [comment]
Sorry - Have you figure it out? @vinifr

**Comment by vinifr** [comment]
I found the answer here: https://stackoverflow.com/a/73597380/6513653

prototype       = await page.evaluateHandle("WebSocket.prototype")
socketInstances = await page.queryObjects(prototype)
await page.evaluate('''(instances) => {
  let instance = instances[0];
  instance.send('Hello');
}''', socketInstances)
