### ISSUE TITLE
the bug with pyppeteer

### ISSUE THREAD

**Issue by runningabcd** [pyppeteer/pyppeteer#410]
test url : https://open.jd.com/

use pyppeteer , page content is much less than puppeteer, why?

**Comment by runningabcd** [comment]
give up pyppeteer, start use puppeteer.
Compared to puppeteer, pyppeteer is a child

**Comment by Mattwmaster58** [comment]
It's tough to say for sure, but is likely due to differing Chrome versions. This library requires a lot of upkeep which none of the current maintainers can commit to.
