### ISSUE TITLE
Can't run pyppeteer in local, or on web-based machine such as Replit

### ISSUE THREAD

**Issue by mariussdl** [pyppeteer/pyppeteer#425]
### Hello guys!,

I've tryied to run this relly basic code:
![carbon(1)](https://user-images.githubusercontent.com/70507259/202223990-d2b3b611-817d-4ee2-a149-83755355feee.png)

Then this error occured: " OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail "

I've ran every single command that I found on the web and install many different version of C++ packages. (found this solution too on the web), but nothing helped. Same error everytime.

So, I decided to try it in [Replit](https://repl.it/) (Web-based machine for developement in many different language), but this time this error occured: 
![image](https://user-images.githubusercontent.com/70507259/202225120-c801c071-bc2a-4e2f-9573-679cd3cbf8ba.png)

I'm pretty sure that's not normal.
Thanks, have a good day.

**Comment by MatanDev3** [comment]
i got the same error

**Comment by mariussdl** [comment]
> i got the same error

Pyppeteer is no longer updated. Check README.md for more info. You can use [Playright](https://github.com/microsoft/playwright-python) instead.
