### ISSUE TITLE
Can you increase the chrome version

### ISSUE THREAD

**Issue by nkligang** [pyppeteer/pyppeteer#439]
The current chrome version used by pypuppeter is very old, can you increase the chrome version?

**Comment by SalaFanChik** [comment]
Read docs and you can set pyppeteer_chrome_revision=999644 this version you can download (103)

**Comment by nkligang** [comment]
when I change to later chrome vision, setRequestInterception is not work!

**Comment by Mattwmaster58** [comment]
Done in 2.0.0rc0

> when I change to later chrome vision, setRequestInterception is not work!

This is not surprising, as the library is unmaintained and CDP APIs are always changing. Even now I would say a good chunk of _official puppeteer_ functionality relies on CDP APIs marked experimental.
