### ISSUE TITLE
About Chromium versions that work well

### ISSUE THREAD

**Issue by Sanuki-073** [pyppeteer/pyppeteer#449]
Thanks for a great project for Scraper!

Over the past week, I have been experiencing problems with button clicks and other actions not working with the default download.

I finally confirmed that the following version works:1203661

If you want to use it, you can set it in an environment variable ”PYPPETEER_CHROMIUM_REVISION” or use it as follows
```
PYPPETEER_CHROMIUM_REVISION=1203661 python dailydata_dl_pyppeteer.py
```

If you are having trouble getting it to work, etc., the trick may be to increase the version of Chromium to get it to work.

**Comment by Mattwmaster58** [comment]
2.0.0rc0 (very small hotfix) has bumped the included Chromium release, this tip isn't 
 necessary (until the version becomes outdated again :( )

**Comment by Sanuki-073** [comment]
Thanks for the correction!
If it stops working, I'll just look for a version that works.
