### ISSUE TITLE
Multiload Browser Sessions.

### ISSUE THREAD

**Issue by MadTinker** [pyppeteer/pyppeteer#5]
> [puppeteer/puppeteer#85](https://github.com/puppeteer/puppeteer/issues/85)
> 
> add to Line 110
> https://github.com/miyakogi/pyppeteer/blob/dev/pyppeteer/browser.py#L110
> 
> ```python
> async def newIncognitoPage(self) -> Page:
>     """Make new incognito page on this browser and return its object."""
>     browserContextId = (await self._connection.send(
>         'Target.createBrowserContext', {})).get('browserContextId')
>     targetId = (await self._connection.send(
>         'Target.createTarget',
>         {'url': 'about:blank', 'browserContextId': browserContextId})).get('targetId')
>     target = self._targets.get(targetId)
>     if target is None:
>         raise BrowserError('Failed to create target for page.')
>     if not await target._initializedPromise:
>         raise BrowserError('Failed to create target for page.')
>     page = await target.page()
>     if page is None:
>         raise BrowserError('Failed to create page.')
>     return page, browserContextId
> ```

**Comment by Granitosaurus** [comment]
Could you elaborate on this more?

**Comment by Mattwmaster58** [comment]
The linked issue has the following content:

> Support browser contexts (Target.createBrowserContext) so to avoid launching multiple instances if one wants a pristine session. See proposal #66 and original discussion at cyrus-and/chrome-remote-interface#118.
> 
> A viable user scenario might be testing several users logged in simultaneously into the service.
We might expose browser contexts as a string literal option to the browser.newPage:
> ```
> browser.newPage(); // creates a new page in a default browser context
> browser.newPage({ context: 'default' }); // same as previous call
> browser.newPage({ context: 'another-context' }); // creates a page in another browser context
> ```

As it stand right now, there isn't any implementation in Puppeteer, and we are trying to focus on feature parity with Puppeteer before anything else, so I think this will have to go on the back burner.

**Comment by MadTinker** [comment]
Sorry I cannot. I was mearly transfering over issues marked as "Todo" in the pyp2 board. 
I have been busy the last few weeks and haven't been at my desk much. 
I have need of the multi-user browser tests, infact one of my main reasons for being here, so I will at some point at least make this a patchable option.
