### ISSUE TITLE
Page.goto returns None instead of exception

### ISSUE THREAD

**Issue by derlin** [pyppeteer/pyppeteer#60]
Hi,
For some URLs, the `goto` method does not fail, but returns `None`. 

For example:
* http://www.swisscamps.ch/de/index.php
* http://www.whisky-club-oberwallis.ch

Here is a minimal example (using pyppeteer2 0.2.2 and Python 3.7.4):

```python
import asyncio
from pyppeteer import launch

urls = [
    'http://www.swisscamps.ch/de/index.php',
    'http://www.whisky-club-oberwallis.ch/brennereien']

async def main():
    browser = await launch(headless=True)
    page = await browser.newPage()
    for url in urls:
        response = await page.goto(url, waitUntil='networkidle0')
        print(url, response)
    await page.close()
    await browser.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Output:
```text
http://www.swisscamps.ch/de/index.php None
http://www.whisky-club-oberwallis.ch None
```

Using urllib3 instead, the same URLs throw an exception:

> Received response with content-encoding: gzip, but failed to decode it. Error -3 while decompressing data: incorrect header check

Would it be possible to throw exceptions instead, or at least say in the documentation `None` is a possible return values ?

To me, this is especially problematic since `puppeteer` has this note [in the documentation](https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-pagegotourl-options):

> NOTE page.goto either throws an error or returns a main resource response. The only exceptions are navigation to about:blank or navigation to the same URL with a different hash, which would succeed and return null.

**Comment by Granitosaurus** [comment]
Weird, I'm looking through puppeteer 2.1.1 and it _can_ return `null`:

```javascript
  navigationResponse() {
    return this._navigationRequest ? this._navigationRequest.response() : null;
  }
```
The only time that would happen however is if navigation request would fail silently and that would happen as per your quoted docs if the request __is not__ a navigation request, e.g. `about:blank`.

Your example does seem to fail because some error passes silently, in this case it seems like decoding issue.

I think `pup2.1.1` branch should auto resolve this when it's finished.

**Comment by Mattwmaster58** [comment]
> I think pup2.1.1 branch should auto resolve this when it's finished.

I think this is 100% the case, I took a look at the 2.1.1 implementation and it does seem to return the response, but the current one does not. @derlin watch #16

**Comment by Mattwmaster58** [comment]
Closing this for now because this has been implemented in the `pup2.1.1` branch. Feel free to reopen if the issue persists after #16 lands and is released.
