### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by leadscloud** [pyppeteer/pyppeteer#70]
https://github.com/miyakogi/pyppeteer/issues/219

**Comment by Mattwmaster58** [comment]
For reference:
> 
>
>    >This is a problem of urllib3 (1.25).
>    >Workaround is to use older version of it:
>    >
>    >pip install -U "urllib3<1.25"
>
> this works for me.
>
> but
>
> ERROR: pyppeteer2 0.2.2 has requirement urllib3<2.0.0,>=1.25.8, but you'll have urllib3 1.24.3 which is incompatible.

**Comment by Mattwmaster58** [comment]
[Apparently this issue was solved in 1.25.5](https://github.com/psf/requests/issues/5204)

**Comment by Mattwmaster58** [comment]
What version of python are you using @leadscloud ? If `3.7 <= version < 3.7.4` then that could be your issue.

**Comment by leadscloud** [comment]
Python 3.7.3, when i cancel first download, then i install pyppeteer2, when start download chromium, the error occur.    

i use  `pip install -U "urllib3<1.25"` to fix it.

but `ERROR: pyppeteer2 0.2.2 has requirement urllib3<2.0.0,>=1.25.8, but you'll have urllib3 1.24.3 which is incompatible.`

this warning not affect my use.

**Comment by Mattwmaster58** [comment]
Check out this comment on the relevant urllib3 bug: https://github.com/urllib3/urllib3/issues/1682#issuecomment-533311857

It's a bug in Python 3.7.3 and earlier. Please upgrade Python and report if the issue persists.

**Comment by leadscloud** [comment]
very tanks.  solved!
