### ISSUE TITLE
How to catch JavaScript / Network issues

### ISSUE THREAD

**Issue by TimurNurlygayanov** [pyppeteer/pyppeteer#71]
Hi, thank you for pyppeteer2!

I'm trying to scrap webpages with JS support, and during the scraping, I also want to track all JavaScript errors, like on this page: https://javascript.info/try-catch (when I open this page in Chrome, I can see two JS errors in my console in DevTools, like "TypeError: Cannot read property 'querySelectorAll' of null")

I'm trying to catch the same errors with pyppeteer2, but no luck so far:

```
import asyncio
from pyppeteer import launch


async def main():
    browser = await launch()
    page = await browser.newPage()

    def logme(msg):
        print(msg)
        print(msg.text, msg.type)

    page.on('console', logme)
    page.on('javascript', logme)
    page.on('pageerror', logme)
    page.on('error', logme)
    await page.goto('https://javascript.info/try-catch')

    await page.content()

    await browser.close()


asyncio.get_event_loop().run_until_complete(main())
```

Is it possible to do? How can I get all JS errors after rendering the page?

**Comment by TimurNurlygayanov** [comment]
I've found the root of the issue: JE errors on this page were caused by my plugins, so when I open the same page in Firefox there are no JS errors.

I've tried another page and managed to catch JS errors with the following code:

```
import asyncio
from pyppeteer import launch


async def main():
    browser = await launch()
    page = await browser.newPage()

    def log_js_error(msg):
        print(msg)

    page.on('pageerror', log_js_error)
    page.on('error', log_js_error)

    response = await page.goto('https://software-testing.ru/')

    await browser.close()


asyncio.get_event_loop().run_until_complete(main())

```

**Comment by Granitosaurus** [comment]
Great to see you solve the issue so promtly and thanks for the follow up.
I'm closing this thread but feel free to comeback if something breaks!
