### ISSUE TITLE
UTF-8 characters are coming as garbage

### ISSUE THREAD

**Issue by bazinga012** [pyppeteer/pyppeteer#72]
Hi all,
I'm using pyppeteer2==0.2.2. UTF-8 characters are coming as garbage. I have tried setting

await page.setExtraHTTPHeaders({'Accept-Charset': 'utf-8', 'Content-Type': 'text/html; charset=utf-8',})
but it doesn't work. Any help is appreciated.

**Comment by Mattwmaster58** [comment]
Could you provide code to reproduce the issue?

**Comment by shubhpy** [comment]
@Mattwmaster58  I am also experiencing this issue where the Indian rupee sign (₹) is there is in HTML body text but it is coming as [] in PDF.

Below is the code I am using.

```
async def request_interceptor(request):
    print("url called: ", request.url, " headers: ", request.headers)
    await request.continue_()

def update_headers(headers):
    default_headers = {
            'Accept-Charset': 'utf-8',
            'Content-Type': 'text/html; charset=utf-8'
    }
    if headers is not None:
        headers.update(default_headers)

async def main(html=None, url=None, headers=None, custom_styles=None):
    browser = await launch(args=['--no-sandbox'], headless=True, handleSIGINT=False, dumpio=False, logLevel='ERROR', handleSIGTERM=False, handleSIGHUP=False)
    page = await browser.newPage()
    update_headers(headers)
    await page.setExtraHTTPHeaders(headers)
    if html:
        await page.setContent(html)
    else:
        await page.setRequestInterception(True)
        page.on('request', lambda request: asyncio.ensure_future(request_interceptor(request)))
        response = await page.goto(url, {'waitUntil': 'networkidle2'})
        if response.status != 200:
            await browser.close()
            return None
        await page.waitFor(1000)
    await page.emulateMedia('screen')
    if custom_styles:
        await page.addStyleTag(custom_styles)
    pdf = await page.pdf({"printBackground": True, "format": 'A4', 'margin': {'bottom': 0}, })
    await browser.close()
    return pdf
```

**Comment by Mattwmaster58** [comment]
@shubhpy That's probably a separate issue altogether and at first glance seems _likely_ to be Chromium's fault, could you open a separate issue?

**Comment by Mattwmaster58** [comment]
@bazinga012 What platform are you on? If windows, it's entirely possible that the characters are being received correctly, but being displayed incorrectly by Windows' terminal.

**Comment by bazinga012** [comment]
We were running pyppeteer inside docker. For utf-8 characters we also need to install few font packages. 


> RUN apt-get install -y fonts-deva fonts-deva-extra fonts-gujr fonts-gujr-extra fonts-indic fonts-noto fonts-noto-cjk

Adding above line on our Dockerfile resolved the issue.
